services:
  postgres:
    image: postgres:16
    container_name: reservation-prod-postgres
    environment:
      POSTGRES_DB: reservation_db
      POSTGRES_USER: reservation_app
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

volumes:
  postgres_prod_data:
